INSERT INTO VENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('123', 'ATT');
INSERT INTO VENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('112', 'WaterCo');
INSERT INTO BILL (VENDOR_ID, BILL_TYPE, PAY_DAY, AMOUNT) VALUES ('123', 'Reccurring', now(),15);
INSERT INTO BILL (VENDOR_ID, BILL_TYPE, PAY_DAY, AMOUNT) VALUES ('112', 'OneOff', now(), 10);
INSERT INTO BILL (VENDOR_ID, BILL_TYPE, PAY_DAY, AMOUNT) VALUES ('112', 'Reccurring', now(), 50);
